feat: test
warsawReact/invoicing-app pull request #2
Opened 2021-11-26 08:52 UTC by warsawReact

test pull request

2021-11-26 09:00 UTC, Sverdiyev approved these changes
Looks good :)

2021-11-26 09:41 UTC, tomaszdanczak reviewed
Looks good :)

2021-11-26 09:42 UTC, tomaszdanczak approved these changes

2021-11-27 18:11 UTC, KowalewskiPawel requested changes
It's definitely better to ignore this branch and not merge it :) Otherwise, maybe you can add a brief description so at least it will gain some value :)

2021-11-29 19:22 UTC, closed without merging